export const MAIN_ROUTE = '/'
export const ACCOUNT_ROUTE = '/account/*'
export const USERS_ROUTE = 'users'
export const GROUPS_ROUTE = 'groups'
export const PLACES_ROUTE = 'places'
export const TESTS_ROUTE = 'tests'
export const PRESS_TEST_ROUTE = '/press'
export const TRIAL_TEST_ROUTE = '/trial'